spring.application.name=multi-amigos
spring.config.import=optional:file:.env[.properties],optional:file:./multi-amigos/.env[.properties]

spring.profiles.active=dev

server.forward-headers-strategy=framework
